### ISSUE TITLE
Builds are not available to download after a week

### ISSUE THREAD

**Issue by SanjayMallur** [DeployGate/upload-app-bitrise-step#12]
When we upload android builds to deploygate, the link to download the apk is expired after a week. This is happening because of the expiration time mentioned in the URL. Where we can change this time?

Example download link: https://d2fjxyapcfdbwq.cloudfront.net/binaries/Global/60170/3553_36f6f68e67fd951c20520fbbf0fb31/app-name-production-release-bitrise-signed.apk?Expires=1606306514&Signature=XXX&Key-Pair-Id=XXX

**Comment by jmatsu** [comment]
@SanjayMallur 
The intended purpose of the CDN links is for fast-download but not for sharing, so the expiration time is not change-able.  Share-able links are available through *Distribution Page* feature. 

ref: What is a distribution page? - https://deploygate.zendesk.com/hc/en-us/articles/360015362320-What-is-distribution-page-

Of course, you can use *Distribution Page* through our step. Our step is very simple, it's just like a thin wrapper of `curl`. Please check `step.yml` in this repository and the API reference(https://docs.deploygate.com/reference#upload)
