### ISSUE TITLE
Getting issue "authenticated"

### ISSUE THREAD

**Issue by minhchienwikipedia** [DeployGate/upload-app-bitrise-step#13]
Hi, I already setup the build & key for Deploygate. If the owner of Deploygate key push code & build it's success. 
But if someone trigger build it's getting an error  `{"message":"you are not authenticated","because":"you are not authenticated","error":true}` 
I getting error when try using gitlab to trigger build

**Comment by jmatsu** [comment]
@minhchienwikipedia 
Could you please check if the api key and/or app owner name are correct? Our step doesn't depend on users who trigger the build. 
In addition, please check the secret variable configuration in Bitrise if used. Some of the users forgot to make the secret available for pull requests. Please note that it's unavailable by default.

**Comment by minhchienwikipedia** [comment]
@jmatsu thanks for your support, I'll check it again

**Comment by jmatsu** [comment]
@minhchienwikipedia 
Any updates?

**Comment by jmatsu** [comment]
Please re-open or create a new issue if you have a problem.
