### ISSUE TITLE
about Deploygate Upload Step

### ISSUE THREAD

**Issue by pa-hisayuki-kishino** [DeployGate/upload-app-bitrise-step#30]
An issue occurred where the Deploygate link destination URL was rewritten in Bitrise's Deploygate step.
The corresponding Bitrise log is below.

Has there ever been a case in the past where the upload URL changed even though the Bitrise Deploygate step settings were unchanged?
If so, please let me know the cause and solution.

Looking at the information below, I feel that setting a distribution key can prevent this kind of phenomenon, but are you aware of this?

https://docs.deploygate.com/docs/api/application/upload/

**Comment by satsukies** [comment]
@pa-hisayuki-kishino 
Thank you for your report.

> The corresponding Bitrise log is below.

I cannot find the bitrise log, so please attach it?

Thank you for your cooperation.

**Comment by pa-hisayuki-kishino** [comment]
@satsukies 

Sorry, I was planning to attach the log, but it contained confidential information, so I didn't attach it.

We are currently inquiring with Deploygate and received information that the distribution page was deleted on 2024/02/29.

It is still unclear why it was deleted, but once it is revealed, this issue will be resolved, so we will close it for now.

If we receive information from Deploygate that indicates that cooperation with Bitrise is questionable, we will reopen the site.
